# -*- coding: utf-8 -*-
"""turkiyedekiuniversiteharitasi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q4qO9JOanRv8tMi-iM-lIFeg0crJ_Bf_
"""

import pandas as pd
import folium
import branca.colormap as cm

# Şehir verileri
cities_data = [
    {'name': 'Adana', 'latitude': 37.0000, 'longitude': 35.3213, 'plate_code': 1},
    {'name': 'Adıyaman', 'latitude': 37.7648, 'longitude': 38.2786, 'plate_code': 2},
    {'name': 'Afyonkarahisar', 'latitude': 38.7500, 'longitude': 30.5333, 'plate_code': 3},
    {'name': 'Ağrı', 'latitude': 39.7188, 'longitude': 43.0526, 'plate_code': 4},
    {'name': 'Amasya', 'latitude': 40.6558, 'longitude': 35.8360, 'plate_code': 5},
    {'name': 'Ankara', 'latitude': 39.9334, 'longitude': 32.8597, 'plate_code': 6},
    {'name': 'Antalya', 'latitude': 36.8969, 'longitude': 30.7133, 'plate_code': 7},
    {'name': 'Artvin', 'latitude': 41.1818, 'longitude': 41.8173, 'plate_code': 8},
    {'name': 'Aydın', 'latitude': 37.8466, 'longitude': 27.8452, 'plate_code': 9},
    {'name': 'Balıkesir', 'latitude': 39.6483, 'longitude': 27.8906, 'plate_code': 10},
    {'name': 'Bilecik', 'latitude': 40.1437, 'longitude': 29.9880, 'plate_code': 11},
    {'name': 'Bingöl', 'latitude': 38.8953, 'longitude': 40.4907, 'plate_code': 12},
    {'name': 'Bitlis', 'latitude': 38.4057, 'longitude': 42.1009, 'plate_code': 13},
    {'name': 'Bolu', 'latitude': 40.7303, 'longitude': 31.6095, 'plate_code': 14},
    {'name': 'Burdur', 'latitude': 37.7202, 'longitude': 30.2917, 'plate_code': 15},
    {'name': 'Bursa', 'latitude': 40.1829, 'longitude': 29.0736, 'plate_code': 16},
    {'name': 'Çanakkale', 'latitude': 40.1500, 'longitude': 26.4167, 'plate_code': 17},
    {'name': 'Çankırı', 'latitude': 40.6053, 'longitude': 33.6190, 'plate_code': 18},
    {'name': 'Çorum', 'latitude': 40.5471, 'longitude': 34.9547, 'plate_code': 19},
    {'name': 'Denizli', 'latitude': 37.7765, 'longitude': 29.0864, 'plate_code': 20},
    {'name': 'Diyarbakır', 'latitude': 37.9100, 'longitude': 40.2336, 'plate_code': 21},
    {'name': 'Edirne', 'latitude': 41.6700, 'longitude': 26.5600, 'plate_code': 22},
    {'name': 'Elazığ', 'latitude': 38.6833, 'longitude': 39.2294, 'plate_code': 23},
    {'name': 'Erzincan', 'latitude': 39.7500, 'longitude': 39.5000, 'plate_code': 24},
    {'name': 'Erzurum', 'latitude': 39.9000, 'longitude': 41.2700, 'plate_code': 25},
    {'name': 'Eskişehir', 'latitude': 39.7767, 'longitude': 30.5206, 'plate_code': 26},
    {'name': 'Gaziantep', 'latitude': 37.0662, 'longitude': 37.3833, 'plate_code': 27},
    {'name': 'Giresun', 'latitude': 40.9167, 'longitude': 38.3833, 'plate_code': 28},
    {'name': 'Gümüşhane', 'latitude': 40.4600, 'longitude': 39.4800, 'plate_code': 29},
    {'name': 'Hakkari', 'latitude': 37.5833, 'longitude': 43.7333, 'plate_code': 30},
    {'name': 'Hatay', 'latitude': 36.2000, 'longitude': 36.1667, 'plate_code': 31},
    {'name': 'Isparta', 'latitude': 37.7667, 'longitude': 30.5500, 'plate_code': 32},
    {'name': 'Mersin', 'latitude': 36.8121, 'longitude': 34.6415, 'plate_code': 33},
    {'name': 'İstanbul', 'latitude': 41.0082, 'longitude': 28.9784, 'plate_code': 34},
    {'name': 'İzmir', 'latitude': 38.4237, 'longitude': 27.1428, 'plate_code': 35},
    {'name': 'Kars', 'latitude': 40.6000, 'longitude': 43.1000, 'plate_code': 36},
    {'name': 'Kastamonu', 'latitude': 41.3833, 'longitude': 33.7833, 'plate_code': 37},
    {'name': 'Kayseri', 'latitude': 38.7203, 'longitude': 35.4827, 'plate_code': 38},
    {'name': 'Kırklareli', 'latitude': 41.7667, 'longitude': 27.2333, 'plate_code': 39},
    {'name': 'Kırşehir', 'latitude': 39.1500, 'longitude': 34.1667, 'plate_code': 40},
    {'name': 'Kocaeli', 'latitude': 40.7667, 'longitude': 29.9167, 'plate_code': 41},
    {'name': 'Konya', 'latitude': 37.8746, 'longitude': 32.4932, 'plate_code': 42},
    {'name': 'Kütahya', 'latitude': 39.4200, 'longitude': 29.9800, 'plate_code': 43},
    {'name': 'Malatya', 'latitude': 38.3550, 'longitude': 38.3350, 'plate_code': 44},
    {'name': 'Manisa', 'latitude': 38.6191, 'longitude': 27.4208, 'plate_code': 45},
    {'name': 'Kahramanmaraş', 'latitude': 37.5852, 'longitude': 36.9382, 'plate_code': 46},
    {'name': 'Mardin', 'latitude': 37.3100, 'longitude': 40.7300, 'plate_code': 47},
    {'name': 'Muğla', 'latitude': 37.2144, 'longitude': 28.3636, 'plate_code': 48},
    {'name': 'Muş', 'latitude': 38.9461, 'longitude': 41.4883, 'plate_code': 49},
    {'name': 'Nevşehir', 'latitude': 38.6200, 'longitude': 34.7100, 'plate_code': 50},
    {'name': 'Niğde', 'latitude': 37.9500, 'longitude': 34.6667, 'plate_code': 51},
    {'name': 'Ordu', 'latitude': 40.9856, 'longitude': 37.8797, 'plate_code': 52},
    {'name': 'Rize', 'latitude': 41.0200, 'longitude': 40.5200, 'plate_code': 53},
    {'name': 'Sakarya', 'latitude': 40.7833, 'longitude': 30.4000, 'plate_code': 54},
    {'name': 'Samsun', 'latitude': 41.2867, 'longitude': 36.3313, 'plate_code': 55},
    {'name': 'Siirt', 'latitude': 37.9300, 'longitude': 41.9500, 'plate_code': 56},
    {'name': 'Sinop', 'latitude': 42.0264, 'longitude': 35.1500, 'plate_code': 57},
    {'name': 'Sivas', 'latitude': 39.7461, 'longitude': 37.0183, 'plate_code': 58},
    {'name': 'Tekirdağ', 'latitude': 40.9833, 'longitude': 27.5167, 'plate_code': 59},
    {'name': 'Tokat', 'latitude': 40.3167, 'longitude': 36.5500, 'plate_code': 60},
    {'name': 'Trabzon', 'latitude': 41.0000, 'longitude': 39.7333, 'plate_code': 61},
    {'name': 'Tunceli', 'latitude': 39.1000, 'longitude': 39.5500, 'plate_code': 62},
    {'name': 'Şanlıurfa', 'latitude': 37.1652, 'longitude': 38.7915, 'plate_code': 63},
    {'name': 'Uşak', 'latitude': 38.6750, 'longitude': 29.4000, 'plate_code': 64},
    {'name': 'Van', 'latitude': 38.4900, 'longitude': 43.3800, 'plate_code': 65},
    {'name': 'Yozgat', 'latitude': 39.8167, 'longitude': 34.8000, 'plate_code': 66},
    {'name': 'Zonguldak', 'latitude': 41.4500, 'longitude': 31.7833, 'plate_code': 67},
    {'name': 'Aksaray', 'latitude': 38.3667, 'longitude': 34.0333, 'plate_code': 68},
    {'name': 'Bayburt', 'latitude': 40.2500, 'longitude': 40.2500, 'plate_code': 69},
    {'name': 'Karaman', 'latitude': 37.1833, 'longitude': 33.2167, 'plate_code': 70},
    {'name': 'Kırıkkale', 'latitude': 39.8500, 'longitude': 33.5167, 'plate_code': 71},
    {'name': 'Batman', 'latitude': 37.8900, 'longitude': 41.1300, 'plate_code': 72},
    {'name': 'Şırnak', 'latitude': 37.5167, 'longitude': 42.4667, 'plate_code': 73},
    {'name': 'Bartın', 'latitude': 41.5833, 'longitude': 32.3333, 'plate_code': 74},
    {'name': 'Ardahan', 'latitude': 41.1167, 'longitude': 42.8167, 'plate_code': 75},
    {'name': 'Iğdır', 'latitude': 39.9167, 'longitude': 44.0333, 'plate_code': 76},
    {'name': 'Yalova', 'latitude': 40.6667, 'longitude': 29.2667, 'plate_code': 77},
    {'name': 'Karabük', 'latitude': 41.2000, 'longitude': 32.6167, 'plate_code': 78},
    {'name': 'Kilis', 'latitude': 36.7000, 'longitude': 37.1167, 'plate_code': 79},
    {'name': 'Osmaniye', 'latitude': 37.2167, 'longitude': 36.2167, 'plate_code': 80},
    {'name': 'Düzce', 'latitude': 40.8333, 'longitude': 31.1667, 'plate_code': 81}
]

# df_cities_base DataFrame'ini oluştur
df_cities_base = pd.DataFrame(cities_data)

# Birleştirme tutarlılığı için şehir adlarını küçük harfe dönüştür
df_cities_base['name_lower'] = df_cities_base['name'].str.lower()

# Üniversite verilerini oku, sütun adlarını temizle
df_universities = pd.read_csv('/content/universiteverileri.csv', sep=',', header=0)
df_universities.columns = df_universities.columns.str.strip()

# İlgili sütunları seç ve yeniden adlandır
df_universities = df_universities[['Üniversite', 'Şehir', 'Resmi Kuruluş Yılı']]
df_universities.columns = ['University Name', 'City', 'Establishment Year']

# `City` sütunundaki NaN değerlerini `.str.lower()`'ı etkinleştirmek için boş dizgeyle doldur
df_universities['City'] = df_universities['City'].fillna('')

# Şehir başına toplam üniversite sayısını say
df_universities_counts = df_universities['City'].value_counts().reset_index()
df_universities_counts.columns = ['City', 'num_universities']

# 2000 yılı öncesi kurulan üniversiteleri filtrele
df_universities_pre2000 = df_universities[df_universities['Establishment Year'] < 2000].copy()

# Şehir başına 2000 yılı öncesi üniversite sayısını say
df_universities_pre2000_counts = df_universities_pre2000['City'].value_counts().reset_index()
df_universities_pre2000_counts.columns = ['City', 'num_universities_pre2000']

# 2000 yılı sonrası kurulan üniversiteleri filtrele
df_universities_post2000 = df_universities[df_universities['Establishment Year'] >= 2000].copy()

# Şehir başına 2000 yılı sonrası üniversite sayısını say
df_universities_post2000_counts = df_universities_post2000['City'].value_counts().reset_index()
df_universities_post2000_counts.columns = ['City', 'num_universities_post2000']

# Birleştirme tutarlılığı için şehir adlarını küçük harfe dönüştür
df_universities_counts['City_lower'] = df_universities_counts['City'].str.lower()
df_universities_pre2000_counts['City_lower'] = df_universities_pre2000_counts['City'].str.lower()
df_universities_post2000_counts['City_lower'] = df_universities_post2000_counts['City'].str.lower()

# Nüfus verilerini oku ve işle
df_population = pd.read_csv('/content/ilnufuslari.csv', sep=';')
# Sütun adlarını temizle
df_population.columns = df_population.columns.str.strip().str.replace(' ', '_').str.replace('(', '').str.replace(')', '').str.replace('.', '').str.replace(',', '')

# En son yılın verilerini al
latest_year = df_population['Time_period_TIME_PERIOD'].max()
df_population_latest = df_population[df_population['Time_period_TIME_PERIOD'] == latest_year].copy()

# 'Türkiye' gibi toplu toplamları filtrele
df_population_latest = df_population_latest[~df_population_latest['Place_of_residence__T'].isin(['Türkiye', 'Total'])]

# İlgili sütunları seç ve yeniden adlandır
df_population_latest = df_population_latest[['Place_of_residence__T', 'Observation']]
df_population_latest.columns = ['City_Name_Population', 'Population']

# Birleştirme için şehir adlarını küçük harfe dönüştür
df_population_latest['City_Name_Population_lower'] = df_population_latest['City_Name_Population'].str.lower()


# df_cities_base'i toplam üniversite sayılarıyla birleştir
df_cities = pd.merge(df_cities_base, df_universities_counts[['City_lower', 'num_universities']],
                     left_on='name_lower', right_on='City_lower', how='left')

# Üniversite olmayan şehirler için NaN değerlerini 0 ile doldur
df_cities['num_universities'] = df_cities['num_universities'].fillna(0).astype(int)

# 2000 öncesi üniversite sayılarıyla birleştir
df_cities = pd.merge(df_cities, df_universities_pre2000_counts[['City_lower', 'num_universities_pre2000']],
                     left_on='name_lower', right_on='City_lower', how='left', suffixes=('_total', '_pre2000'))

# 2000 öncesi üniversite olmayan şehirler için NaN değerlerini 0 ile doldur
df_cities['num_universities_pre2000'] = df_cities['num_universities_pre2000'].fillna(0).astype(int)

# 2000 sonrası üniversite sayılarıyla birleştir
df_cities = pd.merge(df_cities, df_universities_post2000_counts[['City_lower', 'num_universities_post2000']],
                     left_on='name_lower', right_on='City_lower', how='left')

# 2000 sonrası üniversite olmayan şehirler için NaN değerlerini 0 ile doldur
df_cities['num_universities_post2000'] = df_cities['num_universities_post2000'].fillna(0).astype(int)

# df_cities ile nüfus verilerini birleştir
df_cities = pd.merge(df_cities, df_population_latest[['City_Name_Population_lower', 'Population']],
                     left_on='name_lower', right_on='City_Name_Population_lower', how='left')

# NaN nüfus değerlerini 0 ile doldur
df_cities['Population'] = df_cities['Population'].fillna(0).astype(int)

# Nüfus başına üniversite oranını hesapla
df_cities['universities_per_population'] = df_cities.apply(lambda row:
    row['num_universities'] / row['Population'] if row['Population'] > 0 else 0,
    axis=1
)

# Geçici sütunları bırak
df_cities = df_cities.drop(columns=['City_lower', 'City_Name_Population_lower'], errors='ignore')

# --- Tüm üniversiteler katmanı için aralık ve renk haritası belirle
min_universities_all = df_cities['num_universities'].min()
max_universities_all = df_cities['num_universities'].max()
custom_colormap_all = cm.LinearColormap(['yellow', 'orange', 'red'],
                                       vmin=min_universities_all,
                                       vmax=max_universities_all)

# --- 2000 öncesi üniversiteler katmanı için aralık ve renk haritası belirle
min_universities_pre2000 = df_cities['num_universities_pre2000'].min()
max_universities_pre2000 = df_cities['num_universities_pre2000'].max()
# Aynı renk şemasını kullanarak görsel ayrımı sağla, ancak kendi veri aralığına göre ölçekle
custom_colormap_pre2000 = cm.LinearColormap(['yellow', 'orange', 'red'],
                                            vmin=min_universities_pre2000,
                                            vmax=max_universities_pre2000)

# --- 2000 sonrası üniversiteler katmanı için aralık ve renk haritası belirle
min_universities_post2000 = df_cities['num_universities_post2000'].min()
max_universities_post2000 = df_cities['num_universities_post2000'].max()
custom_colormap_post2000 = cm.LinearColormap(['yellow', 'orange', 'red'],
                                             vmin=min_universities_post2000,
                                             vmax=max_universities_post2000)

# Türkiye merkezli yeni bir Folium haritası oluştur
m = folium.Map(location=[38.9637, 35.2433], zoom_start=6)

# Haritaya özel renk skalalarını ekle (isteğe bağlı olarak her biri için ayrı efsane eklenebilir)
# custom_colormap_all.add_to(m)
# custom_colormap_pre2000.add_to(m)
# custom_colormap_post2000.add_to(m)

# İl sınırları için GeoJSON yükle
geojason_path = '/content/turkiye-provinces.geojson'

try:
    folium.GeoJson(
        geojason_path,
        name='İl Sınırları',
        style_function=lambda x: {
            'fillColor': '#ffffff00',
            'color': '#888888', # Orta gri
            'weight': 1.0,      # Orta kalınlık
            'fillOpacity': 0.0
        }
    ).add_to(m)
except FileNotFoundError:
    pass # Dosyanın var olduğu onaylandı, burada ayrıntılı yazdırmaya gerek yok
except Exception as e:
    pass # Burada ayrıntılı yazdırmaya gerek yok

# Ölçeklendirme için maksimum üniversite sayısını tanımla (İstanbul'un sayısı)
# df_cities boşsa veya İstanbul yoksa kontrol et
if 'İstanbul' in df_cities['name'].values:
    istanbul_universities_count_all = df_cities[df_cities['name'] == 'İstanbul']['num_universities'].iloc[0]
    istanbul_universities_count_pre2000 = df_cities[df_cities['name'] == 'İstanbul']['num_universities_pre2000'].iloc[0]
    istanbul_universities_count_post2000 = df_cities[df_cities['name'] == 'İstanbul']['num_universities_post2000'].iloc[0]
else:
    istanbul_universities_count_all = 1 # İstanbul bulunamazsa varsayılan bir değer ata veya hatayı işle
    istanbul_universities_count_pre2000 = 1 # İstanbul bulunamazsa varsayılan bir değer ata veya hatayı işle
    istanbul_universities_count_post2000 = 1 # İstanbul bulunamazsa varsayılan bir değer ata veya hatayı işle

# 0 üniversiteli şehirler için taban yarıçapı ve İstanbul için istenen maksimum yarıçapı tanımla
base_radius_pixels = 8
desired_istanbul_max_scaled_radius_pixels = 30

# Üniversite başına yarıçap ölçeklendirme faktörünü hesapla (tüm üniversiteler için)
radius_scale_factor_all = (desired_istanbul_max_scaled_radius_pixels - base_radius_pixels) / istanbul_universities_count_all if istanbul_universities_count_all > 0 else 0

# Üniversite başına yarıçap ölçeklendirme faktörünü hesapla (2000 öncesi üniversiteler için)
radius_scale_factor_pre2000 = (desired_istanbul_max_scaled_radius_pixels - base_radius_pixels) / istanbul_universities_count_pre2000 if istanbul_universities_count_pre2000 > 0 else 0

# Üniversite başına yarıçap ölçeklendirme faktörünü hesapla (2000 sonrası üniversiteler için)
radius_scale_factor_post2000 = (desired_istanbul_max_scaled_radius_pixels - base_radius_pixels) / istanbul_universities_count_post2000 if istanbul_universities_count_post2000 > 0 else 0

# FeatureGroup'ları oluştur
fg_all_universities = folium.FeatureGroup(name='Tüm Üniversiteler', show=True).add_to(m)
fg_pre2000_universities = folium.FeatureGroup(name='2000 Öncesi Kurulan Üniversiteler', show=False).add_to(m)
fg_post2000_universities = folium.FeatureGroup(name='2000 Sonrası Kurulan Üniversiteler', show=False).add_to(m)

# Her şehir için işaretleyiciler ekle
for idx, row in df_cities.iterrows():

    # --- Tüm üniversiteler katmanı için işaretleyici ---
    color_all = custom_colormap_all(row['num_universities'])
    scaled_num_universities_all = min(row['num_universities'], istanbul_universities_count_all)
    radius_px_all = base_radius_pixels + (scaled_num_universities_all * radius_scale_factor_all)

    tooltip_all_layer = (
        f"<b>{row['name']}</b><br>" # Şehir Adı
        f"Toplam Üniversite: {str(row['num_universities'])}<br>" # Toplam Üniversite Sayısı
        f"Nüfus: {row['Population']:,}<br>" # Nüfus, binlik ayracı ile formatlanmış
        f"100.000 Kişiye Düşen Üniversite: {row['universities_per_population'] * 100000:.2f}" # Nüfus başına üniversite, 2 ondalık basamaklı
    )

    folium.CircleMarker(
        location=[row['latitude'], row['longitude']],
        radius=radius_px_all,
        color=color_all,
        fill=True,
        fill_color=color_all,
        fill_opacity=0.8,
        tooltip=folium.Tooltip(tooltip_all_layer, sticky=True, permanent=False)
    ).add_to(fg_all_universities)

    # --- 2000 Öncesi Kurulan Üniversiteler katmanı için işaretleyici (sadece > 0 ise) ---
    if row['num_universities_pre2000'] > 0:
        color_pre2000 = custom_colormap_pre2000(row['num_universities_pre2000'])
        scaled_num_universities_pre2000 = min(row['num_universities_pre2000'], istanbul_universities_count_pre2000)
        radius_px_pre2000 = base_radius_pixels + (scaled_num_universities_pre2000 * radius_scale_factor_pre2000)

        tooltip_pre2000_layer = (
            f"<b>{row['name']}</b><br>"
            f"2000 Öncesi Kurulan Üniversite: {str(row['num_universities_pre2000'])}"
        )

        folium.CircleMarker(
            location=[row['latitude'], row['longitude']],
            radius=radius_px_pre2000,
            color=color_pre2000,
            fill=True,
            fill_color=color_pre2000,
            fill_opacity=0.8,
            tooltip=folium.Tooltip(tooltip_pre2000_layer, sticky=True, permanent=False)
        ).add_to(fg_pre2000_universities)

    # --- 2000 Sonrası Kurulan Üniversiteler katmanı için işaretleyici (sadece > 0 ise) ---
    if row['num_universities_post2000'] > 0:
        color_post2000 = custom_colormap_post2000(row['num_universities_post2000'])
        scaled_num_universities_post2000 = min(row['num_universities_post2000'], istanbul_universities_count_post2000)
        radius_px_post2000 = base_radius_pixels + (scaled_num_universities_post2000 * radius_scale_factor_post2000)

        tooltip_post2000_layer = (
            f"<b>{row['name']}</b><br>"
            f"2000 Sonrası Kurulan Üniversite: {str(row['num_universities_post2000'])}"
        )

        folium.CircleMarker(
            location=[row['latitude'], row['longitude']],
            radius=radius_px_post2000,
            color=color_post2000,
            fill=True,
            fill_color=color_post2000,
            fill_opacity=0.8,
            tooltip=folium.Tooltip(tooltip_post2000_layer, sticky=True, permanent=False)
        ).add_to(fg_post2000_universities)

# Katman kontrolünü haritaya ekle
folium.LayerControl().add_to(m)

m.save("index.html")