# -*- coding: utf-8 -*-
"""türkiyedekiüniversiteharitası.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q4qO9JOanRv8tMi-iM-lIFeg0crJ_Bf_
"""

import pandas as pd
import folium
import branca.colormap as cm

# Şehirler için veriler
cities_data = [
    {'name': 'Adana', 'latitude': 37.0000, 'longitude': 35.3213, 'plate_code': 1},
    {'name': 'Adıyaman', 'latitude': 37.7648, 'longitude': 38.2786, 'plate_code': 2},
    {'name': 'Afyonkarahisar', 'latitude': 38.7500, 'longitude': 30.5333, 'plate_code': 3},
    {'name': 'Ağrı', 'latitude': 39.7188, 'longitude': 43.0526, 'plate_code': 4},
    {'name': 'Amasya', 'latitude': 40.6558, 'longitude': 35.8360, 'plate_code': 5},
    {'name': 'Ankara', 'latitude': 39.9334, 'longitude': 32.8597, 'plate_code': 6},
    {'name': 'Antalya', 'latitude': 36.8969, 'longitude': 30.7133, 'plate_code': 7},
    {'name': 'Artvin', 'latitude': 41.1818, 'longitude': 41.8173, 'plate_code': 8},
    {'name': 'Aydın', 'latitude': 37.8466, 'longitude': 27.8452, 'plate_code': 9},
    {'name': 'Balıkesir', 'latitude': 39.6483, 'longitude': 27.8906, 'plate_code': 10},
    {'name': 'Bilecik', 'latitude': 40.1437, 'longitude': 29.9880, 'plate_code': 11},
    {'name': 'Bingöl', 'latitude': 38.8953, 'longitude': 40.4907, 'plate_code': 12},
    {'name': 'Bitlis', 'latitude': 38.4057, 'longitude': 42.1009, 'plate_code': 13},
    {'name': 'Bolu', 'latitude': 40.7303, 'longitude': 31.6095, 'plate_code': 14},
    {'name': 'Burdur', 'latitude': 37.7202, 'longitude': 30.2917, 'plate_code': 15},
    {'name': 'Bursa', 'latitude': 40.1829, 'longitude': 29.0736, 'plate_code': 16},
    {'name': 'Çanakkale', 'latitude': 40.1500, 'longitude': 26.4167, 'plate_code': 17},
    {'name': 'Çankırı', 'latitude': 40.6053, 'longitude': 33.6190, 'plate_code': 18},
    {'name': 'Çorum', 'latitude': 40.5471, 'longitude': 34.9547, 'plate_code': 19},
    {'name': 'Denizli', 'latitude': 37.7765, 'longitude': 29.0864, 'plate_code': 20},
    {'name': 'Diyarbakır', 'latitude': 37.9100, 'longitude': 40.2336, 'plate_code': 21},
    {'name': 'Edirne', 'latitude': 41.6700, 'longitude': 26.5600, 'plate_code': 22},
    {'name': 'Elazığ', 'latitude': 38.6833, 'longitude': 39.2294, 'plate_code': 23},
    {'name': 'Erzincan', 'latitude': 39.7500, 'longitude': 39.5000, 'plate_code': 24},
    {'name': 'Erzurum', 'latitude': 39.9000, 'longitude': 41.2700, 'plate_code': 25},
    {'name': 'Eskişehir', 'latitude': 39.7767, 'longitude': 30.5206, 'plate_code': 26},
    {'name': 'Gaziantep', 'latitude': 37.0662, 'longitude': 37.3833, 'plate_code': 27},
    {'name': 'Giresun', 'latitude': 40.9167, 'longitude': 38.3833, 'plate_code': 28},
    {'name': 'Gümüşhane', 'latitude': 40.4600, 'longitude': 39.4800, 'plate_code': 29},
    {'name': 'Hakkari', 'latitude': 37.5833, 'longitude': 43.7333, 'plate_code': 30},
    {'name': 'Hatay', 'latitude': 36.2000, 'longitude': 36.1667, 'plate_code': 31},
    {'name': 'Isparta', 'latitude': 37.7667, 'longitude': 30.5500, 'plate_code': 32},
    {'name': 'Mersin', 'latitude': 36.8121, 'longitude': 34.6415, 'plate_code': 33},
    {'name': 'İstanbul', 'latitude': 41.0082, 'longitude': 28.9784, 'plate_code': 34},
    {'name': 'İzmir', 'latitude': 38.4237, 'longitude': 27.1428, 'plate_code': 35},
    {'name': 'Kars', 'latitude': 40.6000, 'longitude': 43.1000, 'plate_code': 36},
    {'name': 'Kastamonu', 'latitude': 41.3833, 'longitude': 33.7833, 'plate_code': 37},
    {'name': 'Kayseri', 'latitude': 38.7203, 'longitude': 35.4827, 'plate_code': 38},
    {'name': 'Kırklareli', 'latitude': 41.7667, 'longitude': 27.2333, 'plate_code': 39},
    {'name': 'Kırşehir', 'latitude': 39.1500, 'longitude': 34.1667, 'plate_code': 40},
    {'name': 'Kocaeli', 'latitude': 40.7667, 'longitude': 29.9167, 'plate_code': 41},
    {'name': 'Konya', 'latitude': 37.8746, 'longitude': 32.4932, 'plate_code': 42},
    {'name': 'Kütahya', 'latitude': 39.4200, 'longitude': 29.9800, 'plate_code': 43},
    {'name': 'Malatya', 'latitude': 38.3550, 'longitude': 38.3350, 'plate_code': 44},
    {'name': 'Manisa', 'latitude': 38.6191, 'longitude': 27.4208, 'plate_code': 45},
    {'name': 'Kahramanmaraş', 'latitude': 37.5852, 'longitude': 36.9382, 'plate_code': 46},
    {'name': 'Mardin', 'latitude': 37.3100, 'longitude': 40.7300, 'plate_code': 47},
    {'name': 'Muğla', 'latitude': 37.2144, 'longitude': 28.3636, 'plate_code': 48},
    {'name': 'Muş', 'latitude': 38.9461, 'longitude': 41.4883, 'plate_code': 49},
    {'name': 'Nevşehir', 'latitude': 38.6200, 'longitude': 34.7100, 'plate_code': 50},
    {'name': 'Niğde', 'latitude': 37.9500, 'longitude': 34.6667, 'plate_code': 51},
    {'name': 'Ordu', 'latitude': 40.9856, 'longitude': 37.8797, 'plate_code': 52},
    {'name': 'Rize', 'latitude': 41.0200, 'longitude': 40.5200, 'plate_code': 53},
    {'name': 'Sakarya', 'latitude': 40.7833, 'longitude': 30.4000, 'plate_code': 54},
    {'name': 'Samsun', 'latitude': 41.2867, 'longitude': 36.3313, 'plate_code': 55},
    {'name': 'Siirt', 'latitude': 37.9300, 'longitude': 41.9500, 'plate_code': 56},
    {'name': 'Sinop', 'latitude': 42.0264, 'longitude': 35.1500, 'plate_code': 57},
    {'name': 'Sivas', 'latitude': 39.7461, 'longitude': 37.0183, 'plate_code': 58},
    {'name': 'Tekirdağ', 'latitude': 40.9833, 'longitude': 27.5167, 'plate_code': 59},
    {'name': 'Tokat', 'latitude': 40.3167, 'longitude': 36.5500, 'plate_code': 60},
    {'name': 'Trabzon', 'latitude': 41.0000, 'longitude': 39.7333, 'plate_code': 61},
    {'name': 'Tunceli', 'latitude': 39.1000, 'longitude': 39.5500, 'plate_code': 62},
    {'name': 'Şanlıurfa', 'latitude': 37.1652, 'longitude': 38.7915, 'plate_code': 63},
    {'name': 'Uşak', 'latitude': 38.6750, 'longitude': 29.4000, 'plate_code': 64},
    {'name': 'Van', 'latitude': 38.4900, 'longitude': 43.3800, 'plate_code': 65},
    {'name': 'Yozgat', 'latitude': 39.8167, 'longitude': 34.8000, 'plate_code': 66},
    {'name': 'Zonguldak', 'latitude': 41.4500, 'longitude': 31.7833, 'plate_code': 67},
    {'name': 'Aksaray', 'latitude': 38.3667, 'longitude': 34.0333, 'plate_code': 68},
    {'name': 'Bayburt', 'latitude': 40.2500, 'longitude': 40.2500, 'plate_code': 69},
    {'name': 'Karaman', 'latitude': 37.1833, 'longitude': 33.2167, 'plate_code': 70},
    {'name': 'Kırıkkale', 'latitude': 39.8500, 'longitude': 33.5167, 'plate_code': 71},
    {'name': 'Batman', 'latitude': 37.8900, 'longitude': 41.1300, 'plate_code': 72},
    {'name': 'Şırnak', 'latitude': 37.5167, 'longitude': 42.4667, 'plate_code': 73},
    {'name': 'Bartın', 'latitude': 41.5833, 'longitude': 32.3333, 'plate_code': 74},
    {'name': 'Ardahan', 'latitude': 41.1167, 'longitude': 42.8167, 'plate_code': 75},
    {'name': 'Iğdır', 'latitude': 39.9167, 'longitude': 44.0333, 'plate_code': 76},
    {'name': 'Yalova', 'latitude': 40.6667, 'longitude': 29.2667, 'plate_code': 77},
    {'name': 'Karabük', 'latitude': 41.2000, 'longitude': 32.6167, 'plate_code': 78},
    {'name': 'Kilis', 'latitude': 36.7000, 'longitude': 37.1167, 'plate_code': 79},
    {'name': 'Osmaniye', 'latitude': 37.2167, 'longitude': 36.2167, 'plate_code': 80},
    {'name': 'Düzce', 'latitude': 40.8333, 'longitude': 31.1667, 'plate_code': 81}
]

# df_cities_base DataFrame'ini oluştur
df_cities_base = pd.DataFrame(cities_data)

# Birleştirme için şehir adlarını küçük harfe dönüştür
df_cities_base['name_lower'] = df_cities_base['name'].str.lower()

# CSV dosyasını virgül (,) ayırıcı kullanarak ve BAŞLIK SATIRINI okuyarak oku.
df_universities = pd.read_csv('/content/universitesayisi.csv', sep=',', header=0)

# Sadece 'Üniversite' ve 'Şehir' sütunlarını seç ve yeniden adlandır.
df_universities = df_universities[['Üniversite', 'Şehir']]
df_universities.columns = ['University Name', 'City']

# 'City' sütunundaki boş değerleri (NaN) boş string ile doldur,
# çünkü .str.lower() NaN değerlerle çalışamaz。
df_universities['City'] = df_universities['City'].fillna('')

# Şehir başına üniversite sayısını say
df_universities_counts = df_universities['City'].value_counts().reset_index()
df_universities_counts.columns = ['City', 'num_universities']

# Birleştirme tutarlılığı için şehir adlarını küçük harfe dönüştür
df_universities_counts['City_lower'] = df_universities_counts['City'].str.lower()


# Nüfus verilerini oku ve işleme
df_population = pd.read_csv('/content/ilnufuslari.csv', sep=';')
# Sütun isimlerini daha kolay erişim için temizleyelim
df_population.columns = df_population.columns.str.strip().str.replace(' ', '_').str.replace('(', '').str.replace(')', '').str.replace('.', '').str.replace(',', '')

# En son yılın verilerini almak için 'Time_period_TIME_PERIOD' sütununu kontrol edelim
# Genellikle en son yıl en büyük değer olacaktır.
latest_year = df_population['Time_period_TIME_PERIOD'].max()
df_population_latest = df_population[df_population['Time_period_TIME_PERIOD'] == latest_year].copy() # copy() ekledik

# Sadece illerin verilerini almak için 'Türkiye' ve 'Total' gibi genel toplamları filtreleyelim
df_population_latest = df_population_latest[~df_population_latest['Place_of_residence__T'].isin(['Türkiye', 'Total'])]

# İlgili sütunları seç ve yeniden adlandır
df_population_latest = df_population_latest[['Place_of_residence__T', 'Observation']]
df_population_latest.columns = ['City_Name_Population', 'Population']

# Birleştirme için şehir adlarını küçük harfe dönüştür
df_population_latest['City_Name_Population_lower'] = df_population_latest['City_Name_Population'].str.lower()


# df_cities_base DataFrame'ini üniversite sayılarıyla birleştir
# Birleştirme için df_cities_base'deki 'name_lower' sütunu kullanılır
df_cities = pd.merge(df_cities_base, df_universities_counts[['City_lower', 'num_universities']],
                     left_on='name_lower', right_on='City_lower', how='left')

# Üniversite olmayan şehirler için 'num_universities' içindeki NaN değerlerini 0 ile doldur
df_cities['num_universities'] = df_cities['num_universities'].fillna(0).astype(int)

# Nüfus verilerini df_cities ile birleştir
df_cities = pd.merge(df_cities, df_population_latest[['City_Name_Population_lower', 'Population']],
                     left_on='name_lower', right_on='City_Name_Population_lower', how='left')

# Nüfusu olmayan şehirler için NaN değerlerini 0 ile doldur
df_cities['Population'] = df_cities['Population'].fillna(0).astype(int)

# Üniversite/Nüfus oranını hesapla
# Nüfusu 0 olan şehirler için oranı 0 olarak ayarla (bölme hatasını önlemek için)
df_cities['universities_per_population'] = df_cities.apply(lambda row:
    row['num_universities'] / row['Population'] if row['Population'] > 0 else 0,
    axis=1
)

# Gerekmiyorsa geçici 'City_lower' ve 'City_Name_Population_lower' sütunlarını bırak
df_cities = df_cities.drop(columns=['City_lower', 'City_Name_Population_lower'], errors='ignore')

# Renk haritası için üniversite sayılarının aralığını belirle
min_universities = df_cities['num_universities'].min()
max_universities = df_cities['num_universities'].max()

# Sarıdan kırmızıya doğrusal bir renk haritası oluştur
# İstenen 'YlOrRd' (Sarı-Turuncu-Kırmızı) şeması kullanılıyor
custom_colormap = cm.LinearColormap(['yellow', 'orange', 'red'],
                                      vmin=min_universities,
                                      vmax=max_universities)

# Türkiye merkezli yeni bir Folium haritası oluşturun
m = folium.Map(location=[38.9637, 35.2433], zoom_start=6)

# Haritaya özel renk skalasını ekleyin
custom_colormap.add_to(m)

# Türkiye il sınırlarını içeren GeoJSON dosyasını yükleyin
geojason_path = '/content/turkiye-provinces.geojson' # Burayı kendi dosya yolunuzla değiştirin

try:
    folium.GeoJson(
        geojason_path,
        name='İl Sınırları',
        style_function=lambda x: {
            'fillColor': '#ffffff00',
            'color': '#7a7a7a', # İl sınırlarını daha belirgin yapmak için biraz daha koyu gri
            'weight': 1.2,      # Çizgi kalınlığı biraz daha artırıldı
            'fillOpacity': 0.0
        }
    ).add_to(m)
    folium.LayerControl().add_to(m)
except FileNotFoundError:
    print(f"Hata: GeoJSON dosyası bulunamadı: {geojason_path}")
    print("Lütfen doğru dosya yolunu belirttiğinizden ve dosyanın mevcut olduğundan emin olun.")
except Exception as e:
    print(f"GeoJSON dosyasını yüklerken bir hata oluştu: {e}")

# Ölçeklendirme amaçları için maksimum üniversite sayısını tanımla (İstanbul'un sayısı)
# df_cities boş olabilir veya İstanbul olmayabilir. Bu durumu kontrol edelim.
if 'İstanbul' in df_cities['name'].values:
    istanbul_universities_count = df_cities[df_cities['name'] == 'İstanbul']['num_universities'].iloc[0]
else:
    istanbul_universities_count = 1 # İstanbul bulunamazsa varsayılan bir değer ata veya hata işle

# 0 üniversiteli şehirler için temel piksel yarıçapını ve İstanbul için istenen maksimum piksel yarıçapını tanımla
base_radius_pixels = 8 # 0 üniversiteli şehirler için yarıçap daha da azaltıldı (farkı artırmak için)
desired_istanbul_max_scaled_radius_pixels = 30 # İstanbul için maksimum yarıçap küçültüldü

# Üniversite başına piksel cinsinden yarıçap ölçeklendirme faktörünü hesapla
# Bu, İstanbul'un (ve daha fazla üniversitesi olan şehirlerin) desired_istanbul_max_scaled_radius_pixels değerini almasını sağlar.
radius_scale_factor_pixels = (desired_istanbul_max_scaled_radius_pixels - base_radius_pixels) / istanbul_universities_count if istanbul_universities_count > 0 else 0

# Her şehir için işaretleyiciler ekleyin
for idx, row in df_cities.iterrows():
    # Üniversite sayısına göre rengi belirle
    color = custom_colormap(row['num_universities'])

    # Üniversite sayısını İstanbul'un üniversite sayısıyla sınırla (maksimum daire büyüklüğü için)
    scaled_num_universities = min(row['num_universities'], istanbul_universities_count)

    # Üniversite sayısına göre dairenin büyüklüğünü belirle (piksel cinsinden)
    radius_px = base_radius_pixels + (scaled_num_universities * radius_scale_factor_pixels)

    # Folium tooltip nesnesi oluştur ve CircleMarker'a ekle
    tooltip_html = (
        f"<b>{row['name']}</b><br>"
        f"Üniversiteler: {str(row['num_universities'])}<br>"
        f"Nüfus: {row['Population']:,}<br>"
        f"100.000 Kişiye Düşen Üniversite: {row['universities_per_population'] * 100000:.2f}"
    )
    folium.CircleMarker(
        location=[row['latitude'], row['longitude']],
        radius=radius_px, # Dinamik olarak belirlenen yarıçapı piksel cinsinden kullan
        color=color,
        fill=True,
        fill_color=color,
        fill_opacity=0.8, # Opaklık hafifçe azaltıldı
        tooltip=folium.Tooltip(tooltip_html, sticky=True, permanent=False)
    ).add_to(m)

m.save("index.html")